language: python
python: 3.6

branches:
  only:
    - master
    - plugin_v1.1

env:
  global:
    - AIRFLOW_GPL_UNIDECODE=yes

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script:
  - pytest tests
